from simdb import SimDB

STORE_NAME = "test-store"
simdb = SimDB(
    url="http://localhost:8080",
    embedder_url="http://localhost:11434/api/embed",
    embedder_model="qwen3-embedding:0.6b",
)

simdb.create_store(STORE_NAME)


docs = [
    "cat",
    "dog",
    "elephant",
    "tiger",
    "whale",
    "dolphin",
    "penguin",
    "eagle",
    "cobra",
    "gorilla",
    "apple",
    "banana",
    "mango",
    "grape",
    "orange",
    "strawberry",
    "watermelon",
    "pineapple",
    "peach",
    "cherry",
    "carrot",
    "broccoli",
    "spinach",
    "tomato",
    "potato",
    "onion",
    "garlic",
    "cucumber",
    "pepper",
    "mushroom",
    "india",
    "japan",
    "brazil",
    "germany",
    "canada",
    "australia",
    "france",
    "nigeria",
    "argentina",
    "thailand",
    "mumbai",
    "tokyo",
    "london",
    "paris",
    "newyork",
    "berlin",
    "sydney",
    "cairo",
    "toronto",
    "bangkok",
    "cricket",
    "football",
    "tennis",
    "basketball",
    "swimming",
    "boxing",
    "cycling",
    "golf",
    "rugby",
    "volleyball",
    "computer",
    "keyboard",
    "monitor",
    "network",
    "server",
    "database",
    "algorithm",
    "compiler",
    "processor",
    "memory",
    "golang",
    "python",
    "javascript",
    "rust",
    "java",
    "typescript",
    "kotlin",
    "swift",
    "haskell",
    "ruby",
    "happy",
    "sad",
    "angry",
    "fearful",
    "surprised",
    "disgusted",
    "anxious",
    "excited",
    "bored",
    "content",
    "sunny",
    "rainy",
    "cloudy",
    "stormy",
    "windy",
    "snowy",
    "foggy",
    "humid",
    "freezing",
    "drought",
]

print(f"Indexing {len(docs)} documents")
for doc in docs:
    simdb.index_document(STORE_NAME, doc)

print("finished indexing documents")
